### ISSUE TITLE
java.lang.NoSuchMethodError after upgrading from 1.1.3 to 1.2.1

### ISSUE THREAD

**Issue by raviteja06** [jkwiecien/EasyImage#42]
java.lang.NoSuchMethodError: No static method openCamera(Landroid/app/Activity;I)V in class Lpl/aprilapps/easyphotopicker/EasyImage; or its super classes (declaration of 'pl.aprilapps.easyphotopicker.EasyImage' appears in /data/app/com.example-2/base.apk:classes15.dex)

I tried doing Invalidate/Restart no luck.

**Comment by jkwiecien** [comment]
Look like anomally. Have you fixed it @raviteja06 ?
